### PR TITLE
Add a tabulated list of models

### PR DESCRIPTION
**Pull request by bobturneruk**
I've done my best to make this complete with all of the information I can get from the SCRC organisation files on GitHub. I suggest that this is merged even with missing information and can be updated later.

### CODE REVIEW

**Comment by soniamitchell** [comment]
I'd suggest putting this table in the Models landing page (hope that makes sense? - just like the SCRC data pipeline page, that needs populating). Then we could have links below it to each model page.

**Review by soniamitchell — COMMENTED** [review]
I'd suggest putting this table in the Models landing page (hope that makes sense? - just like the SCRC data pipeline page, that needs populating). Then we could have links below it to each model page. If you could make these pages now (if you're around) that would be great btw.. we could quickly merge it.. and I could ask the modellers to fill in their pages at the end of this meeting.

**Comment by bobturneruk** [comment]
I've done some of that - I wonder if we'd be duplicating information already in the repository readmes, if we had a page per model here?

**Comment by bobturneruk** [comment]
Thanks BTW - much better to have the list where you suggest!

**Comment by soniamitchell** [comment]
> I've done some of that - I wonder if we'd be duplicating information already in the repository readmes, if we had a page per model here?

True.. but if the information was here, then we'd have a central resource :)

**Review by alysbrett — APPROVED** [review]
From a Zulip message from John Nonweiler: 

Here's the Contact-Tracing software checklist: https://github.com/ScottishCovidResponse/Contact-Tracing-Model/pull/43/files
And Covid_Simulation_Model: https://github.com/ScottishCovidResponse/Covid_Simulation_Model/blob/master/docs/software_checklist.md

John could also check / add the sentence for each model and any other relevant links? I think it could go live and then add more links though so am happy to approve and get lead RSE/model owners to review in parallel. 

It would actually be good to have this page live ASAP as we have our panel session about RSE contributions to covid modelling at 3pm and this would be a good link to share for anyone wanting to look at the 6 models.

**Comment by bobturneruk** [comment]
SORSE was in the back of my mind (see you there). I'll try and get the other information linked in before then.

**Comment by alysbrett** [comment]
Could possibly have a sentence underneath the models table to say "Each model had a lead Research Software Engineer during the RAMP period and they produced a common checklist to assess and record their level of confidence in the software implementations. The completed checklists are linked in the table and the template has been released under a creative commons licence here : https://github.com/ScottishCovidResponse/modelling-resources/blob/main/software-checklist.md

**Pull request merged**
